source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ImageSlideshow_Example' do
    pod "ImageSlideshow", :path => "../"
    pod "ImageSlideshow/AFURL", :path => "../"
    pod "ImageSlideshow/Alamofire", :path => "../"
    pod "ImageSlideshow/SDWebImage", :path => "../"
    pod "ImageSlideshow/Kingfisher", :path => "../"

end

post_install do | installer |
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3'
        end
    end
end
