platform :ios, '10.0'
use_frameworks!

target 'ImageSlideshow_Example' do
    pod "ImageSlideshow", :path => "../"
    pod "ImageSlideshow/AFURL", :path => "../"
    pod "ImageSlideshow/Alamofire", :path => "../"
    pod "ImageSlideshow/SDWebImage", :path => "../"
    pod "ImageSlideshow/Kingfisher", :path => "../"
end
